const ProjectData = [
  {
    id: 1,
    title: "Marketing Agency Design & Implement.",
    description:
      "The redesign of Spark Social's website highlights my user experience design skills as well as the ability to develop in different technical settings. Using Javascript, React, and Figma, I created a functional and visually appealing interface that showcases my versatility and ability to enhance brand online presence.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic:
      "https://i.imgur.com/BMIqhVP_d.webp?maxwidth=1520&fidelity=grand",
    githubRepo: "https://github.com/",
    projectLink: "https://www.sparksocial.agency",
  },
  {
    id: 2,
    title: "Responsive GPT3 Site",
    description:
      "Responsive GPT3 Site is a dynamic web application I built as part of my Software Engineering portfolio. Leveraging the power of JavaScript, React, and CSS, this project showcases the capabilities of OpenAI's GPT-3.5 language model by creating an interactive and adaptive website. Users can engage in natural language conversations with the site, receiving intelligent responses generated by GPT-3.5, while the responsive design ensures an optimal viewing experience across various devices.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Figma"],
    projectPic:
      "https://i.imgur.com/5OR2Tgq_d.webp?maxwidth=760&fidelity=grand",
    githubRepo:
      "https://github.com/Juwan-Hollingsworth/Figma-To-Responsive-Site",
    projectLink: "https://gpt3-responsive.netlify.app/",
  },

  {
    id: 3,
    title: "Banking Application",
    description:
      "The Banking App project is a fully functional web application developed using JavaScript, React, HTML, and CSS. It offers a secure login system to store user credentials and provides a user-friendly interface for performing basic banking operations such as balance inquiries, fund transfers, and transaction history tracking. This project showcases my skills in front-end development and demonstrates my ability to create robust and interactive applications.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic:
      "https://i.imgur.com/dHJa1Bw_d.webp?maxwidth=760&fidelity=grand",
    githubRepo: "https://github.com/Juwan-Hollingsworth/banking-marketing-app",
    projectLink: "https://hsf-bank-app.netlify.app/",
  },
  {
    id: 4,
    title: "Social Media Metrics App",
    description:
      "The Social Media Metrics App is a powerful tool designed to provide users with comprehensive analytics and insights into their social media performance. With real-time data tracking and visualizations, it offers a user-friendly interface for monitoring key metrics such as engagement, follower growth, and post reach across multiple platforms. This project showcases my ability to develop data-driven applications that empower individuals and businesses to optimize their social media strategies for maximum impact.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic:
      "https://i.imgur.com/U3em2hS_d.webp?maxwidth=760&fidelity=grand",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
  {
    id: 5,
    title: "In-browser Game",
    description:
      "CRUD Email Submission is a dynamic web application designed to streamline the process of collecting and managing user emails. With a user-friendly interface, it allows visitors to submit their email addresses, which are then securely stored in a database. The application also provides administrators with the ability to perform CRUD operations, enabling efficient management of the submitted emails for future communication or analysis.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic:
      "https://i.imgur.com/U7tO5nr_d.webp?maxwidth=760&fidelity=grand",
    projectLink: "https://rb.gy/9jh39",
    ghRepo: "https://rb.gy/9jh39",
  },
  {
    id: 6,
    title: "Web3 Crowdfunding Platform",
    description:
      "The Social Media Metrics App is a powerful tool designed to provide users with comprehensive analytics and insights into their social media performance. With real-time data tracking and visualizations, it offers a user-friendly interface for monitoring key metrics such as engagement, follower growth, and post reach across multiple platforms. This project showcases my ability to develop data-driven applications that empower individuals and businesses to optimize their social media strategies for maximum impact.",
    skills: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    projectPic:
      "https://i.imgur.com/MR06TBB_d.webp?maxwidth=760&fidelity=grand",
    githubRepo: "https://github.com/",
    projectLink: "https://rb.gy/9jh39",
  },
];

export default ProjectData;
